'use strict';
const assert=require('node:assert/strict'),{execFileSync}=require('node:child_process'),{fixture}=require('./helpers/engine-fixture.cjs');
const baseline=execFileSync('git',['show','f72c8e4:dhq-engine.js'],{encoding:'utf8'});
(async()=>{const old=fixture(baseline);await old.ctx.App.loadLeagueIntel();assert.equal(old.ctx.App.LI_LOADED,true,JSON.stringify(old.calls));assert(Object.keys(old.ctx.App.LI.playerScores).length>0);console.log('baseline full engine scores',JSON.stringify(old.ctx.App.LI.playerScores));console.log('baseline warnings',JSON.stringify(old.calls.filter(c=>c[0]==='warn')));
 const cache=fixture(baseline);let release;cache.ctx.DhqStorage.idbGet=()=>new Promise(r=>release=r);const pending=cache.ctx.App.loadLICache();cache.state.currentLeagueId='222';release({ts:cache.ctx.Date.now(),leagueId:'222',data:{playerScores:{foreign:999}}});assert.equal(await pending,true);assert.equal(cache.ctx.App.LI.playerScores.foreign,999);console.log('REPRODUCED cache requested under111 accepted222 after await');
 const explicit=fixture(baseline);const activeBefore=JSON.stringify(explicit.state);await explicit.ctx.App.loadLeagueIntel({state:{...explicit.state,currentLeagueId:'222',leagues:[{...explicit.league,league_id:'222'}]}});assert(explicit.calls.some(c=>c[0]==='chain'&&c[1]==='111'));assert.equal(JSON.stringify(explicit.state),activeBefore);console.log('REPRODUCED explicit222 ignored, builds active111 and publishes globalLI');
 const late=fixture(baseline);let finishStats;const held=new Promise(r=>finishStats=r);late.ctx.Sleeper.fetchSeasonStats=async year=>{await held;return late.stats(Number(year));};const running=late.ctx.App.loadLeagueIntel();await new Promise(r=>setTimeout(r,0));late.ctx.S={...late.state,currentLeagueId:'222',rosters:[],leagues:[{...late.league,league_id:'222'}]};late.change();finishStats();await running;const saved=late.writes.find(w=>w[0]==='cache-write'&&w[1].startsWith('dhq_leagueintel'));assert.equal(saved[2].leagueId,'222');assert.equal(late.ctx.App.LI.playerScores['100'],8539);console.log('REPRODUCED old111 build published underB and saved as league222');

})().catch(e=>{console.error(e);process.exitCode=1;});
