'use strict';
const assert=require('node:assert/strict');
const {fixture}=require('../../../../tests/helpers/engine-fixture.cjs');
const clone=v=>JSON.parse(JSON.stringify(v));
const token=id=>'fixture.'+Buffer.from(JSON.stringify({sub:id,app_metadata:{user_id:id,session_version:1},exp:Math.floor(Date.now()/1000)+3600})).toString('base64url')+'.signature';
(async()=>{
const x=fixture();const before=await x.ctx.App.loadLeagueIntel();x.state.players['100'].age=42;const after=await x.ctx.App.loadLeagueIntel();const control=fixture();control.state.players['100'].age=42;const expected=await control.ctx.App.loadLeagueIntel();assert.equal(after.data.playerScores['100'],before.data.playerScores['100']);assert.notEqual(after.data.playerScores['100'],expected.data.playerScores['100']);console.log(JSON.stringify({finding:'in-place player change ignored by ready shortcut',before:before.data.playerScores['100'],actualAfterAge42:after.data.playerScores['100'],expectedAfterAge42:expected.data.playerScores['100']}));
const q=fixture();let release;q.ctx.Sleeper.fetchSeasonStats=year=>new Promise(r=>{(q.waits??=[]).push(()=>r(q.stats(Number(year))));release=()=>q.waits.forEach(fn=>fn());});const a=q.ctx.App.loadLeagueIntel({state:clone(q.state),isCurrent:()=>true});await new Promise(r=>setTimeout(r,0));const b=q.ctx.App.loadLeagueIntel({state:clone(q.state),isCurrent:()=>false});const same=a===b;release();const canceledCallerResult=await b;await a;assert.equal(same,true);assert.equal(canceledCallerResult.leagueId,'111');console.log(JSON.stringify({finding:'coalesced canceled explicit caller resolves successfully',samePromise:same,receivedLeague:canceledCallerResult.leagueId}));
const ownerB='22222222-2222-4222-8222-222222222222',ownerA='11111111-1111-4111-8111-111111111111';const origin=fixture();origin.store.fw_session_v1=JSON.stringify({token:token(ownerB),user:{id:ownerB}});await origin.ctx.App.loadLeagueIntel();const cache=origin.writes.find(w=>w[0]==='cache-write'&&w[1].startsWith('dhq_leagueintel'));const mismatch=fixture();mismatch.store.fw_session_v1=JSON.stringify({token:token(ownerA),user:{id:ownerB}});mismatch.ctx.DhqStorage.idbGet=async key=>key===cache[1]?cache[2]:null;const accepted=await mismatch.ctx.App.loadLICache();assert.equal(accepted,true);console.log(JSON.stringify({finding:'contradictory token owner A and cached user B adopts B cache',acceptedCache:accepted,ready:mismatch.ctx.App.LI_LOADED}));
})().catch(e=>{console.error(e);process.exitCode=1;});
