'use strict';
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'../..');
const token=(id,claims={})=>'fixture.'+Buffer.from(JSON.stringify({sub:id,app_metadata:{user_id:id,session_version:1},exp:1789948800,...claims})).toString('base64url')+'.signature';
function fixture(source, options={}){
 const calls=[],writes=[],events=[],store={fw_session_v1:JSON.stringify({token:token('account-a'),user:{id:'account-a'}})},listeners={};
 const names=['QB','RB','WR','TE','DL','LB','DB','K'];const players={};names.forEach((position,i)=>{players[String(100+i)]={full_name:'Fixture '+position,first_name:'Fixture',last_name:position,position,age:24+i%4,years_exp:3,team:i%2?'KC':'BUF',status:'Active',injury_status:i===1?'IR':null};});
 const league={league_id:'111',name:'Fixture League',season:'2026',scoring_settings:{pass_yd:0.04,pass_td:4,pass_int:-1,rush_yd:0.1,rush_td:6,rec:1,rec_yd:0.1,rec_td:6,idp_tkl_solo:2,idp_sack:4,xpm:1,fgm:3},roster_positions:['QB','RB','WR','TE','DL','LB','DB','K','BN'],settings:{type:2,draft_rounds:4}};
 const state={currentLeagueId:'111',platform:'sleeper',season:'2026',players,leagues:[league],rosters:[{roster_id:1,owner_id:'one',players:Object.keys(players).slice(0,4),settings:{wins:2,losses:1}},{roster_id:2,owner_id:'two',players:Object.keys(players).slice(4),settings:{wins:1,losses:2}}],drafts:[],tradedPicks:[],nflState:{season:'2026',season_type:'regular',week:3},depthCharts:{}};
 const stats=year=>Object.fromEntries(Object.keys(players).map((id,i)=>[id,{gp:year===2026?2:17,pass_yd:i===0?3500:0,pass_td:i===0?24:0,pass_int:i===0?6:0,rush_yd:i===1?1200:0,rush_td:i===1?8:0,rec:i===2?80:i===3?50:0,rec_yd:i===2?1100:i===3?700:0,rec_td:i===2?8:i===3?5:0,idp_tkl_solo:i>=4&&i<=6?70:0,idp_sack:i===4?10:0,xpm:i===7?25:0,fgm:i===7?20:0}]));
 const rows=Object.keys(players).map((id,i)=>({player:{sleeperId:id,name:players[id].full_name,position:players[id].position},value:7500-i*650,overallRank:i+1,positionRank:1}));
 const ctx={console:{log(){},warn(...a){calls.push(['warn',...a.map(String)]);}},Math,Number,Object,Array,Map,Set,WeakMap,Promise,JSON,String,Boolean,Error,AbortController,URL,performance:{now:()=>1000},setTimeout,clearTimeout,localStorage:{getItem:k=>store[k]??null,setItem:(k,v)=>{store[k]=v;writes.push(['local',k,v]);},removeItem:k=>{delete store[k];writes.push(['remove',k]);}},location:{hostname:'dhqfootball.com'},addEventListener:(name,fn)=>{(listeners[name]??=[]).push(fn);},dispatchEvent:e=>events.push(e.type),CustomEvent:class{constructor(type,options){this.type=type;this.detail=options?.detail;}},App:{},S:state,STORAGE_KEYS:{HIST_KEY:id=>'hist:'+id},DhqStorage:{get:()=>null,remove:k=>writes.push(['remove',k]),idbGet:async key=>{calls.push(['cache-read',key]);return null;},idbSet:async(key,value)=>{writes.push(['cache-write',key,value]);return true;}},DhqEvents:{emit:(type,data)=>events.push({type,data})}};
 ctx.atob=atob;ctx.Date=class extends Date{constructor(...args){super(...(args.length?args:['2026-09-20T00:00:00Z']));}static now(){return 1789862400000;}};ctx.window=ctx;
 ctx.fetch=async url=>{calls.push(['fetch',String(url)]);return{ok:true,json:async()=>rows};};ctx.Sleeper={fetchSeasonStats:async year=>{calls.push(['stats',year]);return stats(Number(year));}};
 const provider={getLeagueChain:async(id,season)=>{calls.push(['chain',id,season]);return Array.from({length:5},(_,i)=>({id:id+'-'+(season-i),season:String(season-i)}));},getDraftPicks:async row=>Object.keys(players).map((pid,i)=>({season:row.season,round:Math.floor(i/2)+1,pick_no:i+1,roster_id:i%2+1,pid,name:players[pid].full_name,pos:players[pid].position,team:players[pid].team})),getTransactions:async row=>({trades:[],faab:[{season:row.season,pid:'101',pos:'RB',bid:12}]}),getBracket:async()=>null,getLeagueUsers:async()=>[],refreshTrades:async()=>[]};ctx.DhqProviders={getProvider:()=>provider};
 vm.createContext(ctx);for(const file of ['dhq-core.js','pick-value-model.js'])vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),ctx,{filename:file});vm.runInContext(source||fs.readFileSync(path.join(root,'dhq-engine.js'),'utf8'),ctx,{filename:'dhq-engine.js'});
 return{ctx,state,league,players,stats,rows,calls,writes,events,store,listeners,provider,change:()=>{store.fw_session_v1='account-b-token';(listeners.storage||[]).forEach(fn=>fn({key:'fw_session_v1'}));}};
}
module.exports={fixture,token};
